### ISSUE TITLE
[Feature Request] Make it possible to send mail

### ISSUE THREAD

**Issue by TheGreyDiamond** [Panakotta00/FicsIt-Networks#129]
Make it possible to send mail to the player so it is visible in the mail pane (opened by pressing X). It would be a nice addition so that you can get mail when your factory dies.

**Comment by XilefTech** [comment]
yeah, also could be really useful for other stuff like sending automated reports on how your factory is doing

**Comment by Panakotta00** [comment]
The current system doesn't seem to easily allow that... those mails are not really dynamic and more static...
there could be a system in between that converts that stuff, but I havent found that yet...
If you find some stuff about that, feel free to let me know on the discord. But for now i gonna mark this as closed.
I can re-open if it is realistic to get implemented
