### ISSUE TITLE
trying to change switch state crashes my game

### ISSUE THREAD

**Issue by EnhancedC** [Panakotta00/FicsIt-Networks#141]
when i use 

Main_Switch=component.proxy(component.findComponent(findClass("Build_PowerSwitch_C"))[1])
Main_Switch.isSwitchOn=false

the game crashes

other things like 
print(Main_Switch.isSwitchOn)
work its just when i try and change it to turn it off or on 

Assertion failed: IsInGameThread() [File:D:/ws/SB-lowprio/UE4/Engine/Source/Runtime/Engine/Private/TimerManager.cpp] [Line: 516] 

0x00007ff8d1474b89 KERNELBASE.dll!UnknownFunction []
0x00007fffdc5e6866 FactoryGame-Core-Win64-Shipping.dll!ReportAssert() [d:\ws\sb-lowprio\ue4\engine\source\runtime\core\private\windows\windowsplatformcrashcontext.cpp:1541]
0x00007fffdc5e8d66 FactoryGame-Core-Win64-Shipping.dll!FWindowsErrorOutputDevice::Serialize() [d:\ws\sb-lowprio\ue4\engine\source\runtime\core\private\windows\windowserroroutputdevice.cpp:79]
0x00007fffdc578d3d FactoryGame-Core-Win64-Shipping.dll!FOutputDevice::LogfImpl() [d:\ws\sb-lowprio\ue4\engine\source\runtime\core\private\misc\outputdevice.cpp:61]
0x00007fffdc52888b FactoryGame-Core-Win64-Shipping.dll!AssertFailedImplV() [d:\ws\sb-lowprio\ue4\engine\source\runtime\core\private\misc\assertionmacros.cpp:100]
0x00007fffdc52a4b0 FactoryGame-Core-Win64-Shipping.dll!FDebug::CheckVerifyFailedImpl() [d:\ws\sb-lowprio\ue4\engine\source\runtime\core\private\misc\assertionmacros.cpp:450]
0x00007fffc36220f3 FactoryGame-Engine-Win64-Shipping.dll!FTimerManager::InternalSetTimerForNextTick() [d:\ws\sb-lowprio\ue4\engine\source\runtime\engine\private\timermanager.cpp:516]
0x00007fffb9344f9b FactoryGame-FicsItNetworks-Win64-Shipping.dll!FIN_StaticRef_AFGBuildableCircuitSwitch::FIN_StaticRefProp_Member_isSwitchOn::Set() [C:\Jenkins\workspace\FicsIt-Networks_development\SatisfactoryModLoader\Plugins\FicsItNetworks\Source\FicsItNetworks\Reflection\FINStaticReflectionSource.cpp:992]
0x00007fffb9227cca FactoryGame-FicsItNetworks-Win64-Shipping.dll!FFINPropertySetterFunc::operator()() [C:\Jenkins\workspace\FicsIt-Networks_development\SatisfactoryModLoader\Plugins\FicsItNetworks\Source\FicsItNetworks\Reflection\FINProperty.cpp:59]
0x00007fffb936eb40 FactoryGame-FicsItNetworks-Win64-Shipping.dll!FicsItKernel::Lua::luaFindSetMember() [C:\Jenkins\workspace\FicsIt-Networks_development\SatisfactoryModLoader\Plugins\FicsItNetworks\Source\FicsItNetworks\FicsItKernel\Processor\Lua\LuaRef.cpp:111]
0x00007fffb9142f0b FactoryGame-FicsItNetworks-Win64-Shipping.dll!FicsItKernel::Lua::luaInstanceNewIndex() [C:\Jenkins\workspace\FicsIt-Networks_development\SatisfactoryModLoader\Plugins\FicsItNetworks\Source\FicsItNetworks\FicsItKernel\Processor\Lua\LuaInstance.cpp:186]
0x00007fffb90eed22 FactoryGame-FicsItNetworks-Win64-Shipping.dll!luaD_call() []
0x00007fffb9115310 FactoryGame-FicsItNetworks-Win64-Shipping.dll!luaV_finishset() []
0x00007fffb9116ccb FactoryGame-FicsItNetworks-Win64-Shipping.dll!luaV_execute() []
0x00007fffb90eedce FactoryGame-FicsItNetworks-Win64-Shipping.dll!luaD_call() []
0x00007fffb90ee204 FactoryGame-FicsItNetworks-Win64-Shipping.dll!luaD_rawrunprotected() []
0x00007fffb90ef2d0 FactoryGame-FicsItNetworks-Win64-Shipping.dll!lua_resume() []
0x00007fffb9318acb FactoryGame-FicsItNetworks-Win64-Shipping.dll!UFINLuaProcessor::LuaTick() [C:\Jenkins\workspace\FicsIt-Networks_development\SatisfactoryModLoader\Plugins\FicsItNetworks\Source\FicsItNetworks\FicsItKernel\Processor\Lua\LuaProcessor.cpp:541]
0x00007fffb938f8e9 FactoryGame-FicsItNetworks-Win64-Shipping.dll!FFINLuaProcessorTick::syncTick() [C:\Jenkins\workspace\FicsIt-Networks_development\SatisfactoryModLoader\Plugins\FicsItNetworks\Source\FicsItNetworks\FicsItKernel\Processor\Lua\LuaProcessor.cpp:158]
0x00007fffb9354729 FactoryGame-FicsItNetworks-Win64-Shipping.dll!UFINKernelSystem::Tick() [C:\Jenkins\workspace\FicsIt-Networks_development\SatisfactoryModLoader\Plugins\FicsItNetworks\Source\FicsItNetworks\FicsItKernel\FicsItKernel.cpp:123]
0x00007fffb92d6de7 FactoryGame-FicsItNetworks-Win64-Shipping.dll!AFINComputerCase::Factory_Tick() [C:\Jenkins\workspace\FicsIt-Networks_development\SatisfactoryModLoader\Plugins\FicsItNetworks\Source\FicsItNetworks\Computer\FINComputerCase.cpp:134]
0x00007fffbb993fe4 FactoryGame-FactoryGame-Win64-Shipping.dll!<lambda_643bc97631e1119ca6d24cb4ba21c30f>::operator()() [d:\ws\sb-lowprio\ue4\games\factorygame\source\factorygame\private\fgbuildablesubsystem.cpp:478]
0x00007fffbb974183 FactoryGame-FactoryGame-Win64-Shipping.dll!ParallelForImpl::TParallelForData<TFunctionRef<void __cdecl(int)> >::Process() [d:\ws\sb-lowprio\ue4\engine\source\runtime\core\public\async\parallelfor.h:169]
0x00007fffbb95fe7d FactoryGame-FactoryGame-Win64-Shipping.dll!TGraphTask<ParallelForImpl::TParallelForTask<TFunctionRef<void __cdecl(int)> > >::ExecuteTask() [d:\ws\sb-lowprio\ue4\engine\source\runtime\core\public\async\taskgraphinterfaces.h:849]
0x00007fffdc3fa93a FactoryGame-Core-Win64-Shipping.dll!FTaskThreadAnyThread::ProcessTasksUntilQuit() [d:\ws\sb-lowprio\ue4\engine\source\runtime\core\private\async\taskgraph.cpp:862]
0x00007fffdc3fe3c2 FactoryGame-Core-Win64-Shipping.dll!FTaskThreadBase::Run() [d:\ws\sb-lowprio\ue4\engine\source\runtime\core\private\async\taskgraph.cpp:529]
0x00007fffdc5fcddb FactoryGame-Core-Win64-Shipping.dll!FRunnableThreadWin::Run() [d:\ws\sb-lowprio\ue4\engine\source\runtime\core\private\windows\windowsrunnablethread.cpp:86]
0x00007fffdc5f57f1 FactoryGame-Core-Win64-Shipping.dll!FRunnableThreadWin::GuardedRun() [d:\ws\sb-lowprio\ue4\engine\source\runtime\core\private\windows\windowsrunnablethread.cpp:35]
0x00007ff8d1fa7034 KERNEL32.DLL!UnknownFunction []
0x00007ff8d3ca2651 ntdll.dll!UnknownFunction []

Crash in runnable thread TaskGraphThreadHP 16

**Comment by Skyamoeba** [comment]
Are you using the dev build or latest release?

Reason for this question this has been fixed in dev build 112 you can find the link on discord for the dev build.
See #137 bug report the code.

**Comment by Panakotta00** [comment]
Tho the latest SMM version should have that fix... so maybe the mod version is not up to date?

**Comment by Panakotta00** [comment]
If this still occurs, feel free to reopen the issue
