### ISSUE TITLE
getDocked function doesn't work on truck stations

### ISSUE THREAD

**Issue by NEintime** [Panakotta00/FicsIt-Networks#160]
When calling the `getDocked` function on a truck station, it returns a value of the type userdata, instead of a `WheeledVehicle` object. 

### To Reproduce:
**You need:**
- 1x Computer
  - 1x EEPROM
  - 1x CPU
  - 1x RAM
- 1x Truck station
- 1x Vehicle

**How to reproduce:**
1. Spawn vehicle in the station
2. Run the code

**Code:**
```
truckStation = component.proxy(component.findComponent(findClass('Build_TruckStation_C'))[1])

print(type(truckStation:getDocked()))
```

**Debug files:** 
[SMMDebug.zip](https://github.com/Panakotta00/FicsIt-Networks/files/7093516/SMMDebug.zip)

**Comment by yackimoff** [comment]
Confirming this issue.  `print(truckStation:getDocked())` (without `type`) when a vehicle is at station throws "bad argument ##1 to '?' (Instance is invalid)".
