### ISSUE TITLE
Load FicsIt-Networks on Linux (with Docker)

### ISSUE THREAD

**Issue by Zoeille** [Panakotta00/FicsIt-Networks#161]
Hi! I'm currently using Satisfactory Multipler with docker (https://github.com/wolveix/satisfactory-server)

When I launch the mod on Linux I got this error: 
`[2021.09.04-22.52.55:626][  0]LogModuleManager: Warning: ModuleManager: Unable to load module 'Z:/config/gamefiles/FactoryGame/Mods/FicsItNetworks/Binaries/Win64/FactoryGame-FicsItNetworks-Win64-Shipping.dll' because the file couldn't be loaded by the OS.
[2021.09.04-22.52.55:626][  0]Message dialog closed, result: Ok, title: Message, text: Plugin 'FicsItNetworks' failed to load because module 'FicsItNetworks' could not be loaded.  There may be an operating system error or the module may not be properly set up.
`

I would like to know if a "Linux" version would be possible one day to be able to exec the mod on Linux (Debian)?

Here is the full log error, if you want to try something in the future ;) https://pastebin.com/4E8Kn0CT

**Comment by Panakotta00** [comment]
Linux is not supported and is unlikely to ever be supported as long as the game doesn't support it it self.

I like linux but i rather hate wine, so I could not even really help you.
