### ISSUE TITLE
Vertical flag of labels resets after reload

### ISSUE THREAD

**Issue by yackimoff** [Panakotta00/FicsIt-Networks#162]
**Describe the bug**
When loading a save labels with Vertical flag set beforehand behave as the flag is not set. And it's indeed not set when you edit a label.

Provide the Debug-File you can generate with SMM.

**To Reproduce**
1. Build large control panel.
2. Place Label 2×1 on it.
3. Edit label with Micro Label Tool, set Vertical flag. Observe that the text if turned 90°.
4. Save the game, restart, load.
5. Observe that the text is not turned and the flag is not set.

**Expected behavior**
The flag is persistent.

**Additional context**
dev-build 146

**Comment by RozeDoyanawa** [comment]
This has been fixed in the latest commit to RozeDevelopment. It normally takes a while before it makes it into main branch.
