### ISSUE TITLE
Micro Display's setText("") bug

### ISSUE THREAD

**Issue by ERYK500** [Panakotta00/FicsIt-Networks#166]
**Describe the bug**
Launching micro display's setText method with the "" as an argument makes it's screen go schrödinger-bright (the screen became semi-randomly pitch-black or font-colored(/light-ed)).

**To Reproduce**
1. Build a computer and a module panel with a micro display modue;
2. Connect them together;
3. Set the PC's EEPROM to:
`
component.proxy(--[[the uuid of the panel goes here]]):getModules()[1]:setText("")
 `
4. Run the code;
5. Observe the display.

**Expected behavior**
The display should just be black after running the code above.

**Additional context**
I'm running the game on low graphics settings and lower than my display's native resolution to mantain decent frames.

**Comment by RozeDoyanawa** [comment]
I can not seem to reproduce this bug. It is true that setting "" does not clear the display, and I'll fix that, but the graphics/brightness-issue can not be reproduced here.

**Comment by RozeDoyanawa** [comment]
setText("") now at least clears the text. As I can not reproduce the rendering issue, I might close this.
Patches will be in RozeDevelopment branch until next major release

**Comment by RozeDoyanawa** [comment]
Fixes in #167
