### ISSUE TITLE
Crash after Save and Closing the Game

### ISSUE THREAD

**Issue by SuperDoesi** [Panakotta00/FicsIt-Networks#169]
Since yesterday evening i became this report after save and closing the game i talk with raiden and he says me i have to do this issue 

Satiscrash is my Crashreport 4 times the same
luascript from RaidenR

![20211007221841_1](https://user-images.githubusercontent.com/73004669/136532206-25fb4985-b249-4197-bc58-859c15412f62.jpg)
![20211007222551_1](https://user-images.githubusercontent.com/73004669/136532210-4983d1d6-70ba-47ad-87d5-53323c7c8451.jpg)

[checkOnlineStatus3.txt](https://github.com/Panakotta00/FicsIt-Networks/files/7310069/checkOnlineStatus3.txt)
[Satiscrash.txt](https://github.com/Panakotta00/FicsIt-Networks/files/7310070/Satiscrash.txt)
[storage3.txt](https://github.com/Panakotta00/FicsIt-Networks/files/7310071/storage3.txt)

**Comment by SuperDoesi** [comment]
Yes i run the script for central storage. Wenn i save all its ok the i clone the game the crash. I play with my girlfriend on this map and we send us the last saves and sie cant load the saves if the game crash after savesVon meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Panakotta00 ***@***.***> Datum: 09.10.21  12:41  (GMT+01:00) An: Panakotta00/FicsIt-Networks ***@***.***> Cc: SuperDoesi ***@***.***>, Author ***@***.***> Betreff: Re: [Panakotta00/FicsIt-Networks] Crash after Save and Closing the Game (#169) 
I dont quite understand...
so it crashes when you try to close the game, but not when you save the game?
Like... it only crashes at closing the game when you run that script, or what?

**Comment by Panakotta00** [comment]
I still dont understand your issue really... plz try to use a translator like DeepL or just as in german in the #off-topic channel of this mods discord server
