### ISSUE TITLE
[Feature request] Get user/player coordinates

### ISSUE THREAD

**Issue by jmarshallpresnell** [Panakotta00/FicsIt-Networks#175]
Add a function to retrieve the list of active users and their coordinates in world-space. (If this exists already, I can't seem to find it)

This would be especially useful in both multiplayer and location-based actions, for example to only power hypertube entrances when a user is nearby (or my specific implementaiotn: to auto route a user through a hypertube network), or something more mundane like turning lights on when a user is nearby.

**Comment by Panakotta00** [comment]
There definetly wont be a general function that allowes you to do so... FIN is no magic... tho maybe at some point there will be a player sensore which allows you to do that in a small given area around the sensor... tho nothing solid is in planning, we are focusing on other stuff like visual scripting

**Comment by jmarshallpresnell** [comment]
Thanks! :) Seems weird that it's not readily queryable on request, but Unreal has some very weird things in it!

**Comment by Panakotta00** [comment]
You miss understand something here...
Unreal can do that no problem...
But the mod doesn't expose it...

The mod does not have a scripting interface for the game, it has a scripting interface inside of the game...
Immersion is key...
IRL I can request a list of all humans living on planet earth, right? So you can't do the same in game.

Design decisions on our behalf, not from Unreal
