### ISSUE TITLE
Multiplayer issues

### ISSUE THREAD

**Issue by TheCriSys** [Panakotta00/FicsIt-Networks#177]
Description of the bug:
When client (not host or in single player game) of a multiplayer game (not tested with dedicated server) some bugs can be encountered.

1. Part of texture missing on a network connector added to a building (constructor, foundry, ...)
2. Allowed to connect a thin network cable to a network pole making the host game crash
3. Unable to rename a nic added on a computer with the network manager
4. Unable to rename all micro panels with the network manager (and their UUID is always '000000000000000000000000000000000')
5. Unable to place a hard drive on a computer

Data:
Satisfactory Experimental, Update 5
version EPIC Games 174005.239
Multiplayer game.

Other mods:
-  Pak utility
-  Linear Motion
-  More decorations
-  Fluid Extra
-  Ficsit-Network
-  Full health regeneration
-  MiniMap

Debug file:
none :(

To Reproduce:
1. Download the all mods
2. Join a multiplayer game
3. try to rename a component/link a thin cable to a network pole

Expected behavior:
Ability to rename a component or not be able to link a thin cable to a network pole

Screenshots:
none :(

Additional context:
No problem in solo game or if host of the multiplayer game. Not tested on dedicated servers.

**Comment by Panakotta00** [comment]
I was able to replicate issue 1, 4 and 5.
1 happens for me on the host system too, so its not really a MP issue... the others I am working on...
I was not able to reproduce issue 2 and 3 tho
