### ISSUE TITLE
indicator pole bug

### ISSUE THREAD

**Issue by kfpopeye** [Panakotta00/FicsIt-Networks#179]
Can't seem to set the color of the indicator pole. The following code yields no results or errors. The pole just stays unlit.

```
light = component.proxy("83CB7B3644AD85DEB6DAE1B691055906")
while true do
 light:setColor(1, 0, 0, 5)
 print("red")
 event.pull(1.0)
 light:setColor(0, 1, 0, 5)
 print("green")
 event.pull(1.0)
end
```

**Comment by TheGreyDiamond** [comment]
For me the indicator pole even has a broken texture. I will try to take a picture of that.

**Comment by LeonardSchmitt67** [comment]
yup got the same problem, i try to set the color but no change to the pole

**Comment by Panakotta00** [comment]
we know about the indicator pole and we are not sure what we gonna do... cuz there is some development for an alternative...
i will leave the issue open till it either got fixed or replaced on the dev branch ^^

**Comment by rolfmonitor** [comment]
Seems it stays unsolved yet.
I tried it, and was looking in the net for help.
So it seems to be a bug...

**Comment by Skyamoeba** [comment]
You can use wall panel and use the lit button, that's my workaround at the moment

**Comment by Panakotta00** [comment]
As it will be replaced by the new modular indicator poles in the new update... will mark this issue as closed
