### ISSUE TITLE
Multiplayer issue Client double network wall pole

### ISSUE THREAD

**Issue by Loki1147** [Panakotta00/FicsIt-Networks#189]
**Describe the bug**
As a Client you can not build the double network Pole through Walls.

When you build the Pole it stays at the Hologram. After a few time the Hologram goes away and you don't see the Pole, but the host can see it.

**To Reproduce**
1. Login as a client
2. Try to build a Network Pole

**Expected behavior**
Build the Pole and connect Network Cables

**Screenshots**

**Additional context**
Mods:
Refined Power

**Comment by TheGreyDiamond** [comment]
I can confirm this, I have the same issue
