### ISSUE TITLE
Network Connectors on Freight Platforms

### ISSUE THREAD

**Issue by Sarjuuk** [Panakotta00/FicsIt-Networks#215]
**Describe the bug**
Network Connectors on Freight Platforms are wildly out of place and invisible

**To Reproduce**
1. build a Freight Platform
2. attach a Network Cable to platform

**Expected behavior**
* the Network Connector should be visible
* the Network Connector should be attached to the Freight Platform

**Screenshots**
![grafik](https://user-images.githubusercontent.com/848030/167855483-991b4bce-c927-43d7-b40f-4fab7a363c32.png)

**Comment by Panakotta00** [comment]
You are not even suposed to be able to connect to them via cable like that

**Comment by Sarjuuk** [comment]
Oh?
So how am I supposed to read the inventory of a station?
