### ISSUE TITLE
Crash after playing for a while

### ISSUE THREAD

**Issue by Skyamoeba** [Panakotta00/FicsIt-Networks#223]
**Describe the bug**
Crash after a while of playing/ all computers can be not running and this will still happen.

Provide the Debug-File you can generate with SMM.

**To Reproduce**
Use Roze's build with new Light Poles

**Expected behavior**
Crash after a while

**Screenshots**
N/A

**Additional context**
Think Roze has experienced this also just putting this here to help out solving

Attached SMM Debug Info

Unreal Engine Crash Reporter below:

Version: 188609, IsEditor: No, IsPerforceBuild: No, BuildConfiguration: Shipping, Launcher: Epic, NetMode: Listen Server, IsUsingMods: Yes

Assertion failed: Index>=0 && Index<NumBits [File:D:\ws\SB-lowprio\UE4\Engine\Source\Runtime\Core\Public\Containers/BitArray.h] [Line: 1256]

FactoryGame_Core_Win64_Shipping!AssertFailedImplV() [D:\ws\SB-lowprio\UE4\Engine\Source\Runtime\Core\Private\Misc\AssertionMacros.cpp:104]
FactoryGame_Core_Win64_Shipping!FDebug::CheckVerifyFailedImpl() [D:\ws\SB-lowprio\UE4\Engine\Source\Runtime\Core\Private\Misc\AssertionMacros.cpp:461]
FactoryGame_Engine_Win64_Shipping!FRepLayout::BuildSharedSerializationForRPC() [D:\ws\SB-lowprio\UE4\Engine\Source\Runtime\Engine\Private\RepLayout.cpp:6494]
FactoryGame_ReplicationGraph_Win64_Shipping!UReplicationGraph::ProcessRemoteFunction() [D:\ws\SB-lowprio\UE4\Engine\Plugins\Runtime\ReplicationGraph\Source\Private\ReplicationGraph.cpp:2034]
FactoryGame_Engine_Win64_Shipping!UNetDriver::ProcessRemoteFunction() [D:\ws\SB-lowprio\UE4\Engine\Source\Runtime\Engine\Private\NetDriver.cpp:5820]
FactoryGame_Engine_Win64_Shipping!AActor::CallRemoteFunction() [D:\ws\SB-lowprio\UE4\Engine\Source\Runtime\Engine\Private\Actor.cpp:4447]
FactoryGame_CoreUObject_Win64_Shipping!UObject::ProcessEvent() [D:\ws\SB-lowprio\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1858]
FactoryGame_Engine_Win64_Shipping!AActor::ProcessEvent() [D:\ws\SB-lowprio\UE4\Engine\Source\Runtime\Engine\Private\Actor.cpp:917]
FactoryGame_FicsItNetworks_Win64_Shipping!AFINModularIndicatorPoleModule::SetColor() [H:\Projects\UE\RozeFINAddonsU4\Plugins\FicsItNetworks\Intermediate\Build\Win64\FactoryGame\Inc\FicsItNetworks\FINModularIndicatorPoleModule.gen.cpp:183]
FactoryGame_FicsItNetworks_Win64_Shipping!AFINModularIndicatorPoleModule::execnetFunc_setColor() [H:\Projects\UE\RozeFINAddonsU4\Plugins\FicsItNetworks\Intermediate\Build\Win64\FactoryGame\Inc\FicsItNetworks\FINModularIndicatorPoleModule.gen.cpp:142]
FactoryGame_CoreUObject_Win64_Shipping!UFunction::Invoke() [D:\ws\SB-lowprio\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\Class.cpp:5589]
FactoryGame_CoreUObject_Win64_Shipping!UObject::ProcessEvent() [D:\ws\SB-lowprio\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1992]
FactoryGame_Engine_Win64_Shipping!AActor::ProcessEvent() [D:\ws\SB-lowprio\UE4\Engine\Source\Runtime\Engine\Private\Actor.cpp:917]
FactoryGame_FicsItNetworks_Win64_Shipping!UFINUFunction::Execute() [H:\Projects\UE\RozeFINAddonsU4\Plugins\FicsItNetworks\Source\FicsItNetworks\Reflection\FINUFunction.h:50]
FactoryGame_FicsItNetworks_Win64_Shipping!FicsItKernel::Lua::luaCallFINFunc() [H:\Projects\UE\RozeFINAddonsU4\Plugins\FicsItNetworks\Source\FicsItNetworks\FicsItKernel\Processor\Lua\LuaRef.cpp:48]
FactoryGame_FicsItNetworks_Win64_Shipping!FicsItKernel::Lua::luaInstanceFuncCall() [H:\Projects\UE\RozeFINAddonsU4\Plugins\FicsItNetworks\Source\FicsItNetworks\FicsItKernel\Processor\Lua\LuaInstance.cpp:121]
FactoryGame_FicsItNetworks_Win64_Shipping!luaD_call()
FactoryGame_FicsItNetworks_Win64_Shipping!luaV_execute()
FactoryGame_FicsItNetworks_Win64_Shipping!luaD_call()
FactoryGame_FicsItNetworks_Win64_Shipping!luaV_execute()
FactoryGame_FicsItNetworks_Win64_Shipping!luaD_callnoyield()
FactoryGame_FicsItNetworks_Win64_Shipping!luaD_rawrunprotected()
FactoryGame_FicsItNetworks_Win64_Shipping!lua_resume()
FactoryGame_FicsItNetworks_Win64_Shipping!UFINLuaProcessor::LuaTick() [H:\Projects\UE\RozeFINAddonsU4\Plugins\FicsItNetworks\Source\FicsItNetworks\FicsItKernel\Processor\Lua\LuaProcessor.cpp:557]
FactoryGame_FicsItNetworks_Win64_Shipping!FFINLuaProcessorTick::syncTick() [H:\Projects\UE\RozeFINAddonsU4\Plugins\FicsItNetworks\Source\FicsItNetworks\FicsItKernel\Processor\Lua\LuaProcessor.cpp:169]
FactoryGame_FicsItNetworks_Win64_Shipping!UFINKernelSystem::Tick() [H:\Projects\UE\RozeFINAddonsU4\Plugins\FicsItNetworks\Source\FicsItNetworks\FicsItKernel\FicsItKernel.cpp:123]
FactoryGame_FicsItNetworks_Win64_Shipping!AFINComputerCase::Factory_Tick() [H:\Projects\UE\RozeFINAddonsU4\Plugins\FicsItNetworks\Source\FicsItNetworks\Computer\FINComputerCase.cpp:146]
FactoryGame_FactoryGame_Win64_Shipping!<lambda_9a1b75034c50804c2f23014618340d68>::operator()() [D:\ws\SB-lowprio\UE4\Games\FactoryGame\Source\FactoryGame\Private\FGBuildableSubsystem.cpp:532]
FactoryGame_FactoryGame_Win64_Shipping!ParallelForImpl::TParallelForData<TFunctionRef<void __cdecl(int)> >::Process() [D:\ws\SB-lowprio\UE4\Engine\Source\Runtime\Core\Public\Async\ParallelFor.h:177]
FactoryGame_FactoryGame_Win64_Shipping!TGraphTask<ParallelForImpl::TParallelForTask<TFunctionRef<void __cdecl(int)> > >::ExecuteTask() [D:\ws\SB-lowprio\UE4\Engine\Source\Runtime\Core\Public\Async\TaskGraphInterfaces.h:886]
FactoryGame_Core_Win64_Shipping!FTaskThreadAnyThread::ProcessTasksUntilQuit() [D:\ws\SB-lowprio\UE4\Engine\Source\Runtime\Core\Private\Async\TaskGraph.cpp:887]
FactoryGame_Core_Win64_Shipping!FTaskThreadBase::Run() [D:\ws\SB-lowprio\UE4\Engine\Source\Runtime\Core\Private\Async\TaskGraph.cpp:541]
FactoryGame_Core_Win64_Shipping!FRunnableThreadWin::Run() [D:\ws\SB-lowprio\UE4\Engine\Source\Runtime\Core\Private\Windows\WindowsRunnableThread.cpp:86]

Like version number (for in-dev versions state the build number and the branch)
[SMMDebug_2022-7-15_15-57-0.zip](https://github.com/Panakotta00/FicsIt-Networks/files/9122290/SMMDebug_2022-7-15_15-57-0.zip)

**Comment by RozeDoyanawa** [comment]
This is not the same issue as I had. Its directly related to my indicator poles. Was this in multiplayer? 
The issue seems to stem from AFINModularIndicatorPoleModule::SetColor(). Dunno why I have never got this.

**Comment by Skyamoeba** [comment]
This is in Singleplayer, I got a lot of computers in the world, I did at one point think it was because there was so many running but I switch them all off and it still did it, I reinstalled the mod with your light poles and it's not crashed since I will let you know if it happens again as I go round the world switching the computers back on.

**Comment by Skyamoeba** [comment]
Latest seems to of solved this
