### ISSUE TITLE
No mouse events from Large Screen

### ISSUE THREAD

**Issue by lceWolf** [Panakotta00/FicsIt-Networks#233]
## Problem
Connecting a Large Screen and listening to the corresponding gpu's events does not trigger any mouse events. 

## Expected behaviour
Regular updates for mouse movement, button down and button up

## Additional Info
This works perfectly fine for a computer screen. Running the same code with a large screen attached instead does not work at all.

Minimal example snippet with does *not* work with a large screen
```
local gpu = computer.getPCIDevices(findClass("FINComputerGPU"))[1]
local screen = component.proxy("A7D012744A3673E702BE3FAADC1771EA")

event.listen(gpu)
gpu:bindScreen(screen)   

while true do
    print(event.pull())
end
```

I also tried the paint example. Does not work either

**Comment by Panakotta00** [comment]
a bit odd as i can not reproduce the issue

screen input even on large screen works fine for me...

**Comment by Panakotta00** [comment]
are the client of a multiplayer session?

**Comment by Panakotta00** [comment]
Gotta close because not reproduceable and lack of feedback.
