### ISSUE TITLE
Game crash on latest version (0.3.11)

### ISSUE THREAD

**Issue by etiennetack** [Panakotta00/FicsIt-Networks#240]
**Describe the bug**
Game crash on latest version (0.3.11).

Provide the Debug-File you can generate with SMM.
[SMMDebug_2022-11-28_10-30-48.zip](https://github.com/Panakotta00/FicsIt-Networks/files/10102776/SMMDebug_2022-11-28_10-30-48.zip)

**To Reproduce**
1. Install latest FicsIt-Networks with SMM
2. Launch the game

**Expected behavior**
The game should launch.

**Screenshots**
![image](https://user-images.githubusercontent.com/5456949/204254452-a5f41213-fe37-496d-8612-447e535352da.png)
![image](https://user-images.githubusercontent.com/5456949/204254506-f50ee93b-31dc-40cd-9115-c180e45981a7.png)

**Additional context**
Like version number (for in-dev versions state the build number and the branch)

SML version: latest (3.4.0)
FicsIt-Networks version: latest (0.3.11)
Satisfactory version: CL208976 (with Steam)

To be sure, I've tried launching without others mods.
The game launch with version 0.3.9, but I've others bugs, like being unable to install a drive in a computer.

**Comment by Panakotta00** [comment]
If you use Early Access = Only Available Version is v0.3.9
If you use Experimental = Only Available Version is v0.3.11
