### ISSUE TITLE
Crash on launch 

### ISSUE THREAD

**Issue by Velkyas** [Panakotta00/FicsIt-Networks#241]
Mode installated 

Mod Name                         Mod Reference             Version
FicsIt-Networks                  FicsItNetworks            0.3.11
Inventory Slots +150             InventorySpace3           1.0.1
KUI - UI Lib for Kyris mods      KUI                       1.6.0
Kyris Blueprint Function library KBFL                      1.14.1
Kyris Decor Lib                  KDecoLib                  2.1.1
Kyris Private Lib                KPrivateCodeLib           1.5.1
MAM Enhancer                     MAMTips                   1.0.2
Microwave Power                  MicrowavePower            0.7.0
Modular Load Balancers           LoadBalancers             1.5.8
Modular UI                       ModularUI                 2.0.10
PowerSuit                        PowerSuit                 1.1.1
PowerSuit Modules                ArmorModules              4.0.2
PSM: Flight                      ArmorModules_Flight       2.0.0
Refined Power                    RefinedPower              3.1.5
RefinedRDLib                     RefinedRDLib              1.0.12
Smart!                           SmartFoundations          20.0.558
Unified Grid                     UnifiedGrid               1.0.7
Unlock All Alternate Recipes     UnlockAllAlternateRecipes 2.0.4

Launching the game and then this happen 
![image](https://user-images.githubusercontent.com/51044449/205449918-9d8b316e-5ee3-439c-981f-f3216911e526.png)

i am using the stable version 
[SatisfactoryModManager.zip](https://github.com/Panakotta00/FicsIt-Networks/files/10146865/SatisfactoryModManager.zip)

**Comment by Panakotta00** [comment]
If you are using the Early Access version of the game, install FicsIt-Networks 0.3.9 instead.

To do that, install FIN using SMM, then open the details for it and change the version to 0.3.9.

The newer versions only work on Experimental.

**Comment by Velkyas** [comment]
Thanks you a lot sir for your help have a good day
