### ISSUE TITLE
Manufacturer.getOutputInv() returns wrong number of inventories

### ISSUE THREAD

**Issue by kfpopeye** [Panakotta00/FicsIt-Networks#245]
The following code always seems to return and additional inventory. IE: Blenders have 3 but only have 2 outputs, same with refiners. Particle accelerators and manufacturers show 2 but only have 1 output.

```
invs = Manufacturer:getOutputInv()
print(invs.Size)
```

**Comment by Panakotta00** [comment]
Its not the number of inventories but the number of output slots.
And its set by the game, it just provides the data what the game gives us.
