### ISSUE TITLE
[Feature Request] Allow moveItemStack to swap stacks

### ISSUE THREAD

**Issue by Finadil** [Panakotta00/FicsIt-Networks#248]
It'd be nice if moveItemStack could swap stacks if there's already one in the destination slot.  You can swap by dragging and dropping so I don't see why you couldn't programmatically.  It'd really help when the container's inventory is already full.

**Comment by Panakotta00** [comment]
I was trying to do that, but for some unknown reason the changes you do, dont occur...
So... it is planned but we have some technical difficulties...

**Comment by Panakotta00** [comment]
As update, the function is planned (if not already present) but it is buggy due to some technical reasons.
We hope we can fix the issue with the next game update.
