### ISSUE TITLE
Crash when calling filesystem.path() with a nil value instead of a string

### ISSUE THREAD

**Issue by M-Marvin** [Panakotta00/FicsIt-Networks#250]
The title says everything, if i call filesystem.path with a nil value the game crashes.
For example:
filesystem.path(4, "test", nil)
filesystem.path("test", nil)
both cause crashes.

I have not tested:
filesystem.path(nil)

Here is the crash report:
[CrashReport.zip](https://github.com/Panakotta00/FicsIt-Networks/files/10291087/CrashReport.zip)

**Comment by Feuermurmel** [comment]
Just `filesystem.path(nil)` is enough.
