### ISSUE TITLE
Large Screens from blueprint have reduced distance to accept mouse events

### ISSUE THREAD

**Issue by llamaizing** [Panakotta00/FicsIt-Networks#254]
**Describe the bug**
Large Screens saved to a blueprint and then built from the blueprint seem to have a very short distance away in which they will accept mouse events

**To Reproduce**
* At a Blueprint designer place a basic 4m wall
* Place a Large Screen on the wall
* Save the blueprint
* Place the blueprint elsewhere
* Connect large screen to computer with network cable
* Run code that uses mouse events
  * e.g. this paint example: https://docs.ficsit.app/ficsit-networks/latest/lua/examples/paint.html
* Mouse events won't work unless standing very close to large screen
  * No problem if repeated but not as a blueprint 

**Expected behavior**
A Large Screen placed on a vertical wall will accept mouse events when standing fairly far away (unlike the same if placed from a blueprint, where you need to practically have your nose touching the screen for it to accept the OnMouseMoved event)

**Screenshots**
Screenshot showing how close I am to screen (OnMouseMoved event changes the bg color of the cursor location blue)
![wall_close_up](https://user-images.githubusercontent.com/22111571/213060883-44c7d5b8-9a46-42ca-8b75-64cb879125b6.png)

**Additional context**
EA using FIN version 0.3.12

Problem seems to be the worst if the blueprint is placed with 180 degrees different heading than when created, but I could be imagining things. Distance always seems degraded anyway regardless of placed heading.

With the attached blueprint the middle and top screens send mouse events, but not from very far away. The bottom screen I can't get to work at all. Deleting the console or other screens does not help.
[3 screen console 2x1.zip](https://github.com/Panakotta00/FicsIt-Networks/files/10441126/3.screen.console.2x1.zip)

**Comment by Panakotta00** [comment]
Will close, as I cant reproduce the issue... feel free to reopen if the issue still persists.
