### ISSUE TITLE
Lua code in EEPROM from Blueprint is reset on first save/load

### ISSUE THREAD

**Issue by ForsakenShell** [Panakotta00/FicsIt-Networks#255]
When placing a blueprint with a computer complete with EEPROM and Lua code, a placed instance of the blueprint will have the code and operate properly until the first time the game is loaded after saving the first time.  When the game is loaded, any blueprinted computer will "forget" their code although the console log will still retain it's contents.  

Basic setup to replicate:
i) Build a computer in a bluprinter:  Computer Frame, Lua CPU, RAM, EEPROM
ii) Load the EEPROM with some code such as ``print( 'hello world' )``
iii) Place the blueprint
iv) Save
v) Load
vi) Observe the Lua code window on the computer is now empty

Placed computer now has no Lua code anymore.  Loading it with code now, it will retain the code between saves.

**Comment by Panakotta00** [comment]
This comes from a game bug I already reported [here](https://questions.satisfactorygame.com/post/6378db7fca608e0803525ad1).

You could help to up-vote and give some pressure on that matter ^^

**Comment by ForsakenShell** [comment]
Thanks, for now I will simply not pre-load the blueprinted setup with a coded EEPROM (indeed, or any EEPROM).

**Comment by Panakotta00** [comment]
Will be fixed with Mod 1.0 Release.
