### ISSUE TITLE
[Feature Request] A remote coder

### ISSUE THREAD

**Issue by bloodchild8906** [Panakotta00/FicsIt-Networks#258]
a equipable code editor that first lists the computers in range then after selecting one opens the code editor for that computer, this will aid in stanses where the computer is hidden behind a wall and overall can help the design

**Comment by Panakotta00** [comment]
Not planned, and probably won't implement.

Alternative Planned Features: Remote Screen Driver or Computer Tablet that can use Wireless Network Messages. In addition, maybe Wake-on-LAN.
