### ISSUE TITLE
[Feature request] Add an easiest way to control Railroad Switches

### ISSUE THREAD

**Issue by SoGCuicui** [Panakotta00/FicsIt-Networks#261]
I saw someone asking for adding a way to control doors / gates and I'm definitely for it!

What I also want to be able to connect to the network are the railroad switches controls, so it should be way easier to control them from a computer, depending of some signals state f.e.
Can they be connected in the same way signals are?

Right now it's a bit tedious to select the right switch on a large railroad.

I tried to call stationTrack:getClosestTrackPosition(train:getFirst().location) to be able to find the closest switch from the position of the train currently occupying my block signal, but it returned me back the station's track (the caller itself)... Am I doing something wrong?

**Comment by Panakotta00** [comment]
The next update will contain door controls, but what is the use of beeing able to control the railroad switch?

**Comment by SoGCuicui** [comment]
As you know, actually trains are always taking the shorter way from A to B, basically preventing the possibility of having train parking lots.
Another thing I would like to be able to build is a dedicated railroad for heavy (long) trains, and another one for faster trains, especially on uphill slopes.

I'm aware that these are specific cases that may not be worth the effort, and also that it's already possible to do this, either with the appropriate program (I'm already able to control a railroad switch with FIN only), or by interfacing FIN with Circuitry (which can be "connected" directly to a railroad switch). So I'll understand if you decide to just close this issue. :)

Anyway, I can't way to test the door controls!

**Comment by Panakotta00** [comment]
Uhm, what do you mean with "you are already able to control the railroad switch"?
There is not much to control as to my knowledge, the atomatic trains completely ignore the settings of the railroad switch.
The settings seem to only affect manual train control which can be overwritten by riding the train and then controling the direction.
iirc there is no way currently, to interface with the automatic train system as you try to do.

**Comment by SoGCuicui** [comment]
I can't remember if I've ever managed to force an automatic train to go in the direction I'd decided with FIN, but I'm absolutely sure I've done it with Circuitry, constantly inputing the desired value into the switch :p 
Maybe it's not possible with FIN only, because of the way it works? 🤔

**Comment by Panakotta00** [comment]
Its possible, just tested it, but not with 100% accuracy...
