### ISSUE TITLE
Error when updating to 0.3.13

### ISSUE THREAD

**Issue by Arlen22** [Panakotta00/FicsIt-Networks#264]
**Describe the bug**

When I update to 0.3.13, it gives the error `Plugin 'FicsitNetworks' failed to load because module 'FicsitNetworks' could not be loaded. There may be an operating system error or the module may not be properly set up. `, and then exits. Version 0.3.12 loads properly.

[SMMDebug_2023-8-31_2-11-49.zip](https://github.com/Panakotta00/FicsIt-Networks/files/12481489/SMMDebug_2023-8-31_2-11-49.zip)

**Comment by Arlen22** [comment]
I believe this line in the log file is relevant. 

```
[2023.08.31-02.11.44:906][  0]LogWindows: Failed to load 'C:/Program Files (x86)/Steam/steamapps/common/Satisfactory/FactoryGame/Mods/FicsItNetworks/Binaries/Win64/FactoryGame-FicsItNetworks-Win64-Shipping.dll' (GetLastError=126)
[2023.08.31-02.11.44:907][  0]LogWindows:   Missing import: FactoryGame-EnhancedInput-Win64-Shipping.dll
... 110 lines listing all the folders it looked in
```

**Comment by RozeDoyanawa** [comment]
A miss in the SML version dependency caused the latest update to be marked for U7 (Early Access, as of writing). The latest update is for U8 (Experimental) and will therefore crash any U7 installs. And by the log, it seems you are still on U7.
Downgrade version or switch to experimental, the latter will likely break a lot of other mods currently.

**Comment by Panakotta00** [comment]
SMR should now not download the new version for U7 users
