### ISSUE TITLE
Network Monitor tool can lag the game

### ISSUE THREAD

**Issue by Sarjuuk** [Panakotta00/FicsIt-Networks#267]
**Describe the bug**
Pointing the Network Monitor tool at either of these entities causes it to select all of them across the game world at once. This may lag the game.
Any type of:
* foundation
* wall
* pillar element
* beam

Provide the Debug-File you can generate with SMM.
[SMMDebug_2023-9-3_14-18-40.zip](https://github.com/Panakotta00/FicsIt-Networks/files/12513571/SMMDebug_2023-9-3_14-18-40.zip)

**To Reproduce**
* have an established factory. The bigger the better.
* point the Network Monitor at any foundation, wall, pillar or beam in interaction distance
* note the outline around *everything* and loss of fps depending on the amount of entities

**Expected behavior**
Unsure. Theses entities aren't networkable. Ignore them?
No lag at least.

**Screenshots**
![20230903163607_1](https://github.com/Panakotta00/FicsIt-Networks/assets/848030/f6dcc600-d353-49f4-9eeb-6fffb00d07ab)

**Additional context**
My save file contains about 120k ot the listed entities.
FPS drops from ~50 to ~10.

**Comment by Panakotta00** [comment]
Should be fixed now with 0.3.16
