### ISSUE TITLE
Train time table rule sets ignore setting item filters

### ISSUE THREAD

**Issue by jvanbruegge** [Panakotta00/FicsIt-Networks#268]
**Describe the bug**
`TrainStop:setRuleSet()` ignores load and unload filters of the rule set.

**To Reproduce**
1. Build a computer and connect it with a train station
2. Build a train in the train station
3. Create a timetable in the train with the station
4. Build a container and fill the first slot with any item
5. connect the container to the computer
6. Run this code:
```lua
station = component.proxy(component.findComponent(findClass('Build_TrainStation_C'))[1])
container = component.proxy(component.findComponent(findClass('Build_StorageContainerMk2_C'))[1])
train = station:getTrackGraph():getTrains()[1]
stop = train:getTimeTable():getStops()[1]
rules = stop:getRuleSet()
type = container:getInventories()[1]:getStack(0).item.type
rules.loadFilters = { type }
stop:setRuleSet(rules)
print(type.name)
print(station.name)
print(train:getName())
```

**Expected behavior**
The timetable of the train was changed to add the item in the container as load filter to the stop

**Actual behavior**
The train has the old time table without load filters

**Additional context**
v0.3.15

**Comment by Panakotta00** [comment]
the getStops returns a struct array... which is done by value...
so you have set the stops to the timetable again...
instead of `stop = train:getTimeTable():getStops()[1]`
you should do
```lua
stops = train:getTimeTable():getStops()
stop = stops[1]
[...]
stop:setRuleSet(rules)
train:setStops(stops)
```

**Comment by jvanbruegge** [comment]
Thanks, I will try this later. Btw, calling `train:setStops()` (so without argument) will crash the game. I can get the crash report later as well
