### ISSUE TITLE
[Feature Request] Change sign emission

### ISSUE THREAD

**Issue by OHB** [Panakotta00/FicsIt-Networks#283]
I've tried to figure it out, but I don't know if sign emission would be on the sign, the prefab, or other and whether it would be an int or float. But, the ability to change emission (i.e. brightness) would be reasonable and very useful.

Proposals (depending on where the data belongs):
on the sign: sign:getEmission(out int) and sign:setEmission(int)
on the prefab: sign:getPrefabSignData().emission

I think one could argue that type (matte vs glossy) be supported at the same time. However, I think the counter-argument could be made that whether it is matte or glossy is a hardware choice not a software choice (and therefore wrongly implemented in-game) and so should not be editable programmatically.

**Comment by RozeDoyanawa** [comment]
@OHB Please verify that this functionality have been added and works as expected using the latest development build

**Comment by Panakotta00** [comment]
Closed due to inactivity and possible fix.
