### ISSUE TITLE
Game Crashes when I Try to escape Computer Gui With ESC key

### ISSUE THREAD

**Issue by CanTorun** [Panakotta00/FicsIt-Networks#290]
**Describe the bug**
Game Crashes when I Try to escape Computer Gui With ESC key. Computer has one Lua CPU **no** rams and **No** eprom installed. I think crash is related with missing eprom. When I try with eprom installed ESC key works as expected.

**To Reproduce**
1. Build a computer
2. Attach a CPU (T1) Lua
3. Open Computer GUI with E
4. Hit ESC key on keyboard to close the menu
5. Game Crashes

**Additional context**
I don't know if I correctly genarated debug files, but I will happy to help for further testing. Thanks for great mod!

**Edit :** formatting

**Debug File**
[SMMDebug_2023-12-1_19-58-38.zip](https://github.com/Panakotta00/FicsIt-Networks/files/13531516/SMMDebug_2023-12-1_19-58-38.zip)

**Crash Reporter Output**
> Version: 269772, IsEditor: No, IsPerforceBuild: No, BuildConfiguration: Shipping, Launcher: Steam, NetMode: Listen Server, IsUsingMods: Yes, IsSaveGameEdited: No
> 
> Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000324
> 
> FactoryGame_Core_Win64_Shipping!FString::operator=() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\Core\Public\Containers\UnrealString.h:111]
> FactoryGame_FicsItNetworksLua_Win64_Shipping!UFINLuaRCO::SetLuaEEPROMCode_Implementation() [G:\Projects\Satisfactory\SatisfactoryModLoader\Mods\FicsItNetworks\Source\FicsItNetworksLua\Private\FINLuaRCO.cpp:13]
> FactoryGame_FicsItNetworksLua_Win64_Shipping!UFINLuaRCO::execSetLuaEEPROMCode() [G:\Projects\Satisfactory\SatisfactoryModLoader\Mods\FicsItNetworks\Intermediate\Build\Win64\FactoryGame\Inc\FicsItNetworksLua\UHT\FINLuaRCO.gen.cpp:30]
> FactoryGame_CoreUObject_Win64_Shipping!UFunction::Invoke() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\Class.cpp:6412]
> FactoryGame_CoreUObject_Win64_Shipping!UObject::CallFunction() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1134]
> FactoryGame_CoreUObject_Win64_Shipping!UObject::ProcessContextOpcode() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:3075]
> FactoryGame_CoreUObject_Win64_Shipping!ProcessLocalScriptFunction() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1203]
> FactoryGame_CoreUObject_Win64_Shipping!ProcessScriptFunction<void (__cdecl*)(UObject *,FFrame &,void *)>() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1033]
> FactoryGame_CoreUObject_Win64_Shipping!UObject::execLocalFinalFunction() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:3206]
> FactoryGame_CoreUObject_Win64_Shipping!ProcessLocalScriptFunction() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1203]
> FactoryGame_CoreUObject_Win64_Shipping!UObject::ProcessInternal() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1301]
> FactoryGame_CoreUObject_Win64_Shipping!UFunction::Invoke() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\Class.cpp:6412]
> FactoryGame_CoreUObject_Win64_Shipping!UObject::ProcessEvent() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:2131]
> FactoryGame_UMG_Win64_Shipping!UUserWidget::NativeDestruct() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\UMG\Private\UserWidget.cpp:1450]
> FactoryGame_UMG_Win64_Shipping!SObjectWidget::ResetWidget() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\UMG\Private\Slate\SObjectWidget.cpp:67]
> FactoryGame_UMG_Win64_Shipping!SObjectWidget::~SObjectWidget() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\UMG\Private\Slate\SObjectWidget.cpp:49]
> FactoryGame_SlateCore_Win64_Shipping!FSlotBase::~FSlotBase() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\SlateCore\Private\SlotBase.cpp:111]
> FactoryGame_Slate_Win64_Shipping!SBox::~SBox()
> FactoryGame_SlateCore_Win64_Shipping!FSlotBase::~FSlotBase() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\SlateCore\Private\SlotBase.cpp:111]
> FactoryGame_Slate_Win64_Shipping!SBox::~SBox()
> FactoryGame_SlateCore_Win64_Shipping!FSlotBase::~FSlotBase() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\SlateCore\Private\SlotBase.cpp:111]
> FactoryGame_SlateCore_Win64_Shipping!SBoxPanel::TSlot<SStackBox::FSlot>::`scalar deleting destructor'()
> FactoryGame_SlateCore_Win64_Shipping!SOverlay::~SOverlay()
> FactoryGame_SlateCore_Win64_Shipping!FSlotBase::~FSlotBase() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\SlateCore\Private\SlotBase.cpp:111]
> FactoryGame_Slate_Win64_Shipping!SBox::~SBox()
> FactoryGame_SlateCore_Win64_Shipping!FSlotBase::~FSlotBase() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\SlateCore\Private\SlotBase.cpp:111]
> FactoryGame_SlateCore_Win64_Shipping!SCompoundWidget::~SCompoundWidget()
> FactoryGame_SlateCore_Win64_Shipping!FSlotBase::~FSlotBase() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\SlateCore\Private\SlotBase.cpp:111]
> FactoryGame_Slate_Win64_Shipping!SConstraintCanvas::FSlot::`vector deleting destructor'()
> FactoryGame_Slate_Win64_Shipping!SUniformWrapPanel::~SUniformWrapPanel()
> FactoryGame_SlateCore_Win64_Shipping!FSlotBase::~FSlotBase() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\SlateCore\Private\SlotBase.cpp:111]
> FactoryGame_Slate_Win64_Shipping!SBox::~SBox()
> FactoryGame_UMG_Win64_Shipping!TSharedRef<STextBlock,1>::~TSharedRef<STextBlock,1>() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\Core\Public\Misc\TVariantMeta.h:165]
> FactoryGame_UMG_Win64_Shipping!TSingleWidgetChildrenWithSlot<TSingleWidgetChildrenWithBasicLayoutSlot<0> >::operator[]() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\SlateCore\Public\Layout\Children.h:436]
> FactoryGame_UMG_Win64_Shipping!SObjectWidget::~SObjectWidget() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\UMG\Private\Slate\SObjectWidget.cpp:49]
> FactoryGame_SlateCore_Win64_Shipping!FSlotBase::~FSlotBase() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\SlateCore\Private\SlotBase.cpp:111]
> FactoryGame_Slate_Win64_Shipping!SBox::~SBox()
> FactoryGame_SlateCore_Win64_Shipping!FSlotBase::~FSlotBase() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\SlateCore\Private\SlotBase.cpp:111]
> FactoryGame_SlateCore_Win64_Shipping!SBoxPanel::TSlot<SStackBox::FSlot>::`scalar deleting destructor'()
> FactoryGame_SlateCore_Win64_Shipping!SOverlay::~SOverlay()
> FactoryGame_SlateCore_Win64_Shipping!FSlotBase::~FSlotBase() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\SlateCore\Private\SlotBase.cpp:111]
> FactoryGame_Slate_Win64_Shipping!SConstraintCanvas::FSlot::`vector deleting destructor'()
> FactoryGame_Slate_Win64_Shipping!SUniformWrapPanel::~SUniformWrapPanel()
> FactoryGame_SlateCore_Win64_Shipping!FSlotBase::~FSlotBase() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\SlateCore\Private\SlotBase.cpp:111]
> FactoryGame_SlateCore_Win64_Shipping!SBoxPanel::TSlot<SStackBox::FSlot>::`scalar deleting destructor'()
> FactoryGame_SlateCore_Win64_Shipping!SOverlay::~SOverlay()
> FactoryGame_SlateCore_Win64_Shipping!FSlotBase::~FSlotBase() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\SlateCore\Private\SlotBase.cpp:111]
> FactoryGame_SlateCore_Win64_Shipping!SBoxPanel::TSlot<SStackBox::FSlot>::`scalar deleting destructor'()
> FactoryGame_SlateCore_Win64_Shipping!SOverlay::~SOverlay()
> FactoryGame_UMG_Win64_Shipping!TSharedRef<STextBlock,1>::~TSharedRef<STextBlock,1>() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\Core\Public\Misc\TVariantMeta.h:165]
> FactoryGame_UMG_Win64_Shipping!TSingleWidgetChildrenWithSlot<TSingleWidgetChildrenWithBasicLayoutSlot<0> >::operator[]() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\SlateCore\Public\Layout\Children.h:436]
> FactoryGame_UMG_Win64_Shipping!SObjectWidget::~SObjectWidget() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\UMG\Private\Slate\SObjectWidget.cpp:49]
> FactoryGame_SlateCore_Win64_Shipping!FSlotBase::~FSlotBase() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\SlateCore\Private\SlotBase.cpp:111]
> FactoryGame_Slate_Win64_Shipping!SBox::~SBox()
> FactoryGame_UMG_Win64_Shipping!TSharedRef<STextBlock,1>::~TSharedRef<STextBlock,1>() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\Core\Public\Misc\TVariantMeta.h:165]
> FactoryGame_UMG_Win64_Shipping!TSingleWidgetChildrenWithSlot<TSingleWidgetChildrenWithBasicLayoutSlot<0> >::operator[]() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\SlateCore\Public\Layout\Children.h:436]
> FactoryGame_UMG_Win64_Shipping!SObjectWidget::~SObjectWidget() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\UMG\Private\Slate\SObjectWidget.cpp:49]
> FactoryGame_SlateCore_Win64_Shipping!FSlotBase::~FSlotBase() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\SlateCore\Private\SlotBase.cpp:111]
> FactoryGame_SlateCore_Win64_Shipping!SCompoundWidget::~SCompoundWidget()
> FactoryGame_SlateCore_Win64_Shipping!FSlotBase::~FSlotBase() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\SlateCore\Private\SlotBase.cpp:111]
> FactoryGame_SlateCore_Win64_Shipping!SOverlay::FOverlaySlot::`vector deleting destructor'()
> FactoryGame_SlateCore_Win64_Shipping!SOverlay::~SOverlay()
> FactoryGame_UMG_Win64_Shipping!TSharedRef<STextBlock,1>::~TSharedRef<STextBlock,1>() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\Core\Public\Misc\TVariantMeta.h:165]
> FactoryGame_UMG_Win64_Shipping!TSingleWidgetChildrenWithSlot<TSingleWidgetChildrenWithBasicLayoutSlot<0> >::operator[]() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\SlateCore\Public\Layout\Children.h:436]
> FactoryGame_UMG_Win64_Shipping!SObjectWidget::~SObjectWidget() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\UMG\Private\Slate\SObjectWidget.cpp:49]
> FactoryGame_UMG_Win64_Shipping!UHorizontalBox::OnSlotRemoved() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\UMG\Private\Components\HorizontalBox.cpp:51]
> FactoryGame_UMG_Win64_Shipping!UPanelWidget::RemoveChildAt() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\UMG\Private\Components\PanelWidget.cpp:107]
> FactoryGame_UMG_Win64_Shipping!UPanelWidget::execRemoveChild() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Intermediate\Build\Win64\FactoryGame\Inc\UMG\UHT\PanelWidget.gen.cpp:40]
> FactoryGame_CoreUObject_Win64_Shipping!UFunction::Invoke() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\Class.cpp:6412]
> FactoryGame_CoreUObject_Win64_Shipping!UObject::CallFunction() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1134]
> FactoryGame_CoreUObject_Win64_Shipping!UObject::ProcessContextOpcode() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:3075]
> FactoryGame_CoreUObject_Win64_Shipping!UObject::execLetBool() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:2966]
> FactoryGame_CoreUObject_Win64_Shipping!ProcessLocalScriptFunction() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1203]
> FactoryGame_CoreUObject_Win64_Shipping!ProcessScriptFunction<void (__cdecl*)(UObject *,FFrame &,void *)>() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1033]
> FactoryGame_CoreUObject_Win64_Shipping!UObject::execLocalVirtualFunction() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:3199]
> FactoryGame_CoreUObject_Win64_Shipping!UObject::execLetBool() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:2966]
> FactoryGame_CoreUObject_Win64_Shipping!ProcessLocalScriptFunction() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1203]
> FactoryGame_CoreUObject_Win64_Shipping!ProcessScriptFunction<void (__cdecl*)(UObject *,FFrame &,void *)>() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1033]
> FactoryGame_CoreUObject_Win64_Shipping!UObject::execLocalVirtualFunction() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:3199]
> FactoryGame_CoreUObject_Win64_Shipping!ProcessLocalScriptFunction() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1203]
> FactoryGame_CoreUObject_Win64_Shipping!ProcessScriptFunction<void (__cdecl*)(UObject *,FFrame &,void *)>() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1033]
> FactoryGame_CoreUObject_Win64_Shipping!UObject::execLocalFinalFunction() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:3206]
> FactoryGame_CoreUObject_Win64_Shipping!ProcessLocalScriptFunction() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1203]
> FactoryGame_CoreUObject_Win64_Shipping!UObject::ProcessInternal() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1301]
> FactoryGame_CoreUObject_Win64_Shipping!UFunction::Invoke() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\Class.cpp:6412]
> FactoryGame_CoreUObject_Win64_Shipping!UObject::ProcessEvent() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:2131]
> FactoryGame_CoreUObject_Win64_Shipping!UFunction::Invoke() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\Class.cpp:6412]
> FactoryGame_CoreUObject_Win64_Shipping!UObject::CallFunction() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1134]
> FactoryGame_CoreUObject_Win64_Shipping!ProcessLocalScriptFunction() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1203]
> FactoryGame_CoreUObject_Win64_Shipping!ProcessScriptFunction<void (__cdecl*)(UObject *,FFrame &,void *)>() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1033]
> FactoryGame_CoreUObject_Win64_Shipping!UObject::execLocalFinalFunction() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:3206]
> FactoryGame_CoreUObject_Win64_Shipping!ProcessLocalScriptFunction() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1203]
> FactoryGame_CoreUObject_Win64_Shipping!UObject::ProcessInternal() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1301]
> FactoryGame_CoreUObject_Win64_Shipping!UFunction::Invoke() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\Class.cpp:6412]
> FactoryGame_CoreUObject_Win64_Shipping!UObject::ProcessEvent() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:2131]
> FactoryGame_FactoryGame_Win64_Shipping!TBaseUObjectMethodDelegateInstance<0,AFGBuildableLightSource,void __cdecl(UFGPowerInfoComponent *),FDefaultDelegateUserPolicy>::Execute() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:535]
> FactoryGame_FactoryGame_Win64_Shipping!FEnhancedInputActionEventDelegateBinding<TDelegate<void __cdecl(FInputActionValue const &),FDefaultDelegateUserPolicy> >::Execute() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Plugins\EnhancedInput\Source\EnhancedInput\Public\EnhancedInputComponent.h:301]
> FactoryGame_EnhancedInput_Win64_Shipping!UEnhancedPlayerInput::ProcessInputStack() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Plugins\EnhancedInput\Source\EnhancedInput\Private\EnhancedPlayerInput.cpp:504]
> FactoryGame_FactoryGame_Win64_Shipping!UFGPlayerInput::ProcessInputStack() [C:\BuildAgent\work\78a794e88763017d\UE4\FactoryGame\Source\FactoryGame\Private\FGPlayerInput.cpp:77]
> FactoryGame_Engine_Win64_Shipping!APlayerController::ProcessPlayerInput() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\Engine\Private\PlayerController.cpp:2707]
> FactoryGame_Engine_Win64_Shipping!APlayerController::TickPlayerInput() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\Engine\Private\PlayerController.cpp:4985]
> FactoryGame_Engine_Win64_Shipping!APlayerController::PlayerTick() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\Engine\Private\PlayerController.cpp:2308]
> FactoryGame_FactoryGame_Win64_Shipping!AFGPlayerController::PlayerTick() [C:\BuildAgent\work\78a794e88763017d\UE4\FactoryGame\Source\FactoryGame\Private\FGPlayerController.cpp:315]
> FactoryGame_Engine_Win64_Shipping!APlayerController::TickActor() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\Engine\Private\PlayerController.cpp:5140]
> FactoryGame_Engine_Win64_Shipping!FActorTickFunction::ExecuteTick() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\Engine\Private\Actor.cpp:215]
> FactoryGame_Engine_Win64_Shipping!FTickFunctionTask::DoTask() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\Engine\Private\TickTaskManager.cpp:280]
> FactoryGame_Engine_Win64_Shipping!TGraphTask<FTickFunctionTask>::ExecuteTask() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\Core\Public\Async\TaskGraphInterfaces.h:1315]
> FactoryGame_Core_Win64_Shipping!FNamedTaskThread::ProcessTasksUntilQuit() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\Core\Private\Async\TaskGraph.cpp:648]
> FactoryGame_Core_Win64_Shipping!FTaskGraphCompatibilityImplementation::WaitUntilTasksComplete() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\Core\Private\Async\TaskGraph.cpp:2123]
> FactoryGame_Engine_Win64_Shipping!FTickTaskSequencer::ReleaseTickGroup() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\Engine\Private\TickTaskManager.cpp:560]
> FactoryGame_Engine_Win64_Shipping!FTickTaskManager::RunTickGroup() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\Engine\Private\TickTaskManager.cpp:1595]
> FactoryGame_Engine_Win64_Shipping!UWorld::Tick() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\Engine\Private\LevelTick.cpp:1518]
> FactoryGame_Engine_Win64_Shipping!UGameEngine::Tick() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\Engine\Private\GameEngine.cpp:1795]
> FactoryGame_FactoryGame_Win64_Shipping!UFGGameEngine::Tick() [C:\BuildAgent\work\78a794e88763017d\UE4\FactoryGame\Source\FactoryGame\Private\FGGameEngine.cpp:15]
> FactoryGame_Win64_Shipping!FEngineLoop::Tick() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\Launch\Private\LaunchEngineLoop.cpp:5873]
> FactoryGame_Win64_Shipping!GuardedMain() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\Launch\Private\Launch.cpp:188]
> FactoryGame_Win64_Shipping!GuardedMainWrapper() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:107]
> FactoryGame_Win64_Shipping!LaunchWindowsStartup() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:244]
> FactoryGame_Win64_Shipping!WinMain() [C:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:284]
> FactoryGame_Win64_Shipping!__scrt_common_main_seh() [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
> kernel32
> ntdll

**Comment by PhoneDroid** [comment]
Confirmed the <kbd> ESC </kbd> behavior:

|                | Without CPU | With CPU |
|:--------------:|:-----------:|:--------:|
| Without EEPROM |      -      |  Crash
| With    EEPROM |      -      |    -

**Comment by Panakotta00** [comment]
This issue should be fixed with the latest In-Dev version. Can you try out the latest jenkins build?

**Comment by Panakotta00** [comment]
> I tried it out, had to create a new world to not freeze on the banner that shows up when you load into the world, didn't fix it, still crashes in the same way as before.

Are you sure @PhoneDroid you used the new in-dev version? Dont start it via SMM once installed. Cuz I can not get the issue to replicate anymore.

**Comment by PhoneDroid** [comment]
I just replaced the FIN mod folder content with the content from the zip
![image](https://github.com/Panakotta00/FicsIt-Networks/assets/73050054/e7e56a8d-30e6-454e-8eb8-bb6b807f2298)

And started Satisfactory via Steam

**Comment by Panakotta00** [comment]
Master branch is what is available with SMM... you should download the latest development branch version. @PhoneDroid

**Comment by PhoneDroid** [comment]
Oh, lol, didn't expect the 'here' link in the dev section to redirect to the master artifact, didn't see that .. 

Gonna try it out rn
