### ISSUE TITLE
Network wire is not removed when attached train station is deconstructed, culminating in crash

### ISSUE THREAD

**Issue by FeepingCreature** [Panakotta00/FicsIt-Networks#295]
**Describe the bug**

When deconstructing a train station attached to a computer with a network wire, the network wire is left behind. When trying to deconstruct the computer afterwards, the game segfaults with:

Version: 269772, IsEditor: No, IsPerforceBuild: No, BuildConfiguration: Shipping, Launcher: Epic, NetMode: Listen Server, IsUsingMods: Yes, IsSaveGameEdited: No

Assertion failed: O != 0 [File:C:\Jenkins\workspace\FicsIt-Networks_development\SatisfactoryModLoader\Mods\FicsItNetworks\Intermediate\Build\Win64\FactoryGame\Inc\FicsItNetworks\UHT\FINNetworkCircuitNode.gen.cpp] [Line: 330]

FactoryGame_FicsItNetworks_Win64_Shipping!IFINNetworkCircuitNode::Execute_GetConnected() [C:\Jenkins\workspace\FicsIt-Networks_development\SatisfactoryModLoader\Mods\FicsItNetworks\Intermediate\Build\Win64\FactoryGame\Inc\FicsItNetworks\UHT\FINNetworkCircuitNode.gen.cpp:330]
FactoryGame_FicsItNetworks_Win64_Shipping!AFINNetworkCircuit::IsNodeConnected_Internal() [C:\Jenkins\workspace\FicsIt-Networks_development\SatisfactoryModLoader\Mods\FicsItNetworks\Source\FicsItNetworks\Private\Network\FINNetworkCircuit.cpp:179]

**To Reproduce**

As far as I remember:
- build train station
- build computer
- attach computer to train station with network wire
- deconstruct train station, leaving the network wire hanging in the air
- deconstruct computer

**Expected behavior**

The network wire is removed along with the train station. Alternately, it can still be removed separately.

**Additional context**

This is on development Jenkins #77.

**Comment by Panakotta00** [comment]
I'm unable to reproduce the issue.
Are you 100% certain you started it with the in-dev version? That means after installing the version you have not started the game via SMM, but instead directly (or you started it via SMM with the developer profiler).

**Comment by Dessix** [comment]
This occurred for me directly after recovering a save inaccessible due to #290 via use of the development build from Jenkins run 77; a connected client performed the action, and it took down the listen server but not the client.

**Comment by FeepingCreature** [comment]
(We're in the same game.)

**Comment by Panakotta00** [comment]
Well... It could have to do something with that Mod, simply try it without the mod and you will see.

Also Linux is not officially supported. So there is that.

**Comment by FeepingCreature** [comment]
Sure I mean, feel free to close this, especially since you can't repro. We don't exactly want to go and crash the game so we can try to get it back up for ten minutes either. :P Still, if somebody else runs into it, that crash line will be in Google now.

**Comment by FeepingCreature** [comment]
Correction: Build Gun Utilities was downloaded but we didn't actually have it installed anymore.

**Comment by Dessix** [comment]
> Also Linux is not officially supported. So there is that.

The crash only occurred on the non-Linux host machine, for the record.

**Comment by Panakotta00** [comment]
I still cant reproduce the issue, if you still experience it once the 1.0 update releases. Feel free to reopen the issue.
