### ISSUE TITLE
Docs reference findClass, which is deprecated

### ISSUE THREAD

**Issue by FeepingCreature** [Panakotta00/FicsIt-Networks#296]
On development, the docs for PCIDevices use `findClass("NetworkCard")`. But when you try that, you get a deprecation warning to "use 'classes' global library instead". The 'classes' API does not seem to be documented.

**Comment by EpocDotFr** [comment]
I tried to read [the C++ code](https://github.com/Panakotta00/FicsIt-Networks/blob/master/Source/FicsItNetworksLua/Private/FINLua/LuaClass.cpp) implementing that library to find out how to use the non-deprecated way but, as I have no experience in C++ programming, I don't know how I should use it.

**Comment by EpocDotFr** [comment]
I have read the source code of that `classes` global API, _maybe_ they are now indexed by their name like `classes['NetworkCard']`, but I'm not sure. I'll try this tonight.

**Comment by EpocDotFr** [comment]
It works:

![image](https://github.com/Panakotta00/FicsIt-Networks/assets/2053431/bc45755a-20fb-40c2-8d5a-7955c817e7e6)

**Comment by RozeDoyanawa** [comment]
classes is a list of all available classes. you can use it as a lua table by accessing with [] or by dot, if the name is c++ name compliant, that is, no special characters or dashes.
Eg. classes.NetworkCard works too. We can not publish a complete list of what classes contains, as it depends on what mods you have installed.

**Comment by RozeDoyanawa** [comment]
I'll drop a link to the docs op mentioned, as pana is, afaik, the only one who can update the docs: 
https://docs.ficsit.app/ficsit-networks/latest/lua/examples/PCIDevices.html

**Comment by Panakotta00** [comment]
Will be updated with next mod release.
