### ISSUE TITLE
Network mod crashes with Refined Power mod

### ISSUE THREAD

**Issue by Linrox** [Panakotta00/FicsIt-Networks#310]
Using the Network Manager tool if you click on objects from the Refined Power Mod the game freezes and then ctd.

Provide the Debug-File you can generate with SMM.

1. Build Network Manager tool
2. place an object from refined Power. (Coal furnace or generator mk2)
3. using the Network Manager tool, click on the placed machine from Refined Power.

**Expected behavior**
Game freezes and then crashes

Using latest versions:
Satisfactory: Early access CL#273254
Mod Loader: 3.7.0+V3.7.0.370
Refined Power Mod: 3.2.16
Ficsit Networks Mod: 0.3.19
[FactoryGame.log](https://github.com/Panakotta00/FicsIt-Networks/files/14472606/FactoryGame.log)

**Comment by RozeDoyanawa** [comment]
There is, unfortunately, no crash information in the log.

**Comment by Panakotta00** [comment]
Will close due to inactivity.

As hint, there probably is something faulty with the API implementation o f Refined Power, so you probably need to tell the Refined Power people.

Ensure you are on latest version of FIN and Refined Power.
