### ISSUE TITLE
[Feature Request] Dedicated Server support

### ISSUE THREAD

**Issue by Merith-TK** [Panakotta00/FicsIt-Networks#314]
I run a LinuxServer dedicated, and was hoping the mod could be ported over to LinuxServer if possible, and if not, what are the limitations preventing you from doing so?

**Comment by RozeDoyanawa** [comment]
FicsitNetworks is unfortunately not compatible with either Dedicated Servers nor Linux. Some members in Discord have had various degrees of success getting it to run under linux client with various translation layers. 

The main reason we do not have Dedicated Server support is lack of devs. Neither of the current two main devs plays Multiplayer. I personally can't even test multiplayer.

**Comment by Merith-TK** [comment]
I would be willing to help test and *attempt* to help develop the mod on Dedicated Servers, I do not know much of C varient languages but I do know enough golang and java to be able to understand the formatting and structure of code once I see it (and get the appropriate VSCode extensions). Just need to be able to talk to someone who knows how to help me setup a build environment (The guide on modding website didnt really help me understand the stuff as much as i would've liked)

**Comment by RozeDoyanawa** [comment]
The mod is open source, if you feel like "fixing" it, you "just" have to grab the code and set up the development environment. Do note tho, that part of the network code is in C++ and part is in blueprints.

**Comment by ThatWileyGuy** [comment]
Is this still an issue?

**Comment by Panakotta00** [comment]
Yes but I'm working on and I plan to have the next update contain Windows Dedicated Server Support.

**Comment by ThatWileyGuy** [comment]
Any idea what's blocking Linux support and whether it's something an Unreal-newbie-with-other-C++-experience like me could take a look at?

**Comment by Panakotta00** [comment]
@ThatWileyGuy Simply not tested. For now we focus on Windows Dedicated Servers as this is a lot better supported by Unreal. Once that is done I will start to try to do Linux Native.

**Comment by Merith-TK** [comment]
Best guess is runtime dependancies at the moment.
since windows and linux are vastly different environments, its mostly easy to compile the same engine asset for supported targets, however something like this goes beyond "engine asset" level and is basically whole program level

**Comment by Panakotta00** [comment]
@Merith-TK Most of Unreal Engine code is developed with cross platform in mind. So as long as your code only uses those cross platform types (which you usually do) you wont run into issues.
But in our case we access here and there some Platform specifics. Some are more easy to fixe, some are not. F.e. Windows Filesystem Change Listener.

**Comment by Merith-TK** [comment]
Thanks for the clearification, that is what I was trying to get at but my words were not wanting to cooperate there!

**Comment by Panakotta00** [comment]
There are still some dedicated server specific and MP bugs, but generally there is dedicated server support now.
For both Linux and Windows.

**Comment by jtdossett** [comment]
I've installed on a dedicated linux server. Mod seems to load. The research tree is in the MAM, but none of the milestones are in the hub.

**Comment by Viper-0501** [comment]
there are no milestones in the hub, its only in the MAM now
