### ISSUE TITLE
Factories and containers no longer support >1 network cable connections

### ISSUE THREAD

**Issue by kfpopeye** [Panakotta00/FicsIt-Networks#345]
This just started today (Nov 1, 2024). A couple of my networks started losing factory connections. When I investigated the factories and containers that were daisy chained with 2 network connections no longer showed as connect to 2, only 1 connection. When I tried to reconnect them, there were no more connection available on the factories. When I removed the remaining network connection that was visible and tried to reconnect the factory to a network pole, it still said no more connection available.

I found a work around by removing all the network cables, saving the game, reloading the saved game and then I could connect one network cable to each factory\container again and use FIN network poles or wall sockets to to connect more than one cable to redo the network.

**Comment by murm9000** [comment]
Having this same issue.  It's easily reproducible, and happening on the mini-cables as well. 

1. Place a Sizeable Panel
2. Place a Small Network Plug
3. Connect the Plug to the Panel
4. Dismantle the network cable
5. Try to connect the Plug to the Panel again -- "No empty Power Line connections!"

This happens on many other buildables as well.

**Comment by Panakotta00** [comment]
Fixed with latest update
