### ISSUE TITLE
Using shared code on different computers

### ISSUE THREAD

**Issue by Maxmyd** [Panakotta00/FicsIt-Networks#348]
Hi.
I suggest to allow developers write and save modules which can be re-used on different computers using the LUA "require" directive. Code block (classes and so on) could be saved on the hard drive and imported from user's PC local storage, when needed. 
Sorry, I could not find this feature in documentation. Please let me know if this is already possible.

**Comment by Panakotta00** [comment]
Floppies and Drives are mapped to your Host Computers Filesystem.
There you can easily do multi file development and copy them to other computers.
In game you can only use the data work bench to copy data, like the contents of an eeprom, from one item to the other.

If you dont like this way of sharing code, then sorry...
but you could also write your own small little bootstrap code that loads shared code from another computer using network messages.

**Comment by Maxmyd** [comment]
Hello,
Possibly I have incorrectly formulated the request. The main purpose of my idea is not exactly about sharing the code as a file itself , but about using it with "require" directive to use the code as an executable module.
Anyway, thank you for your reply and efforts. You do a great work.
