### ISSUE TITLE
Dedicated Server - EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000190 - when placing panel controls server CTD

### ISSUE THREAD

**Issue by RaphaelAmbrosiusC0st3au** [Panakotta00/FicsIt-Networks#362]
**Describe the bug**
The servers crashes when new control is placed to the sizeable control panel. Error code is EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000190

**To Reproduce**
1. Place the "Sizeable control panel" (I did 1x2)
2. Add "Indicator"
3. ...server crashes

**Expected behavior**
Be able to create the panel and place any of the available controls.

**Screenshots**
N/A as server crashes.

**Additional context**
Game version: 379322
Mod version: 0.3.29
Windows Server 2019

[stacktrace.txt](https://github.com/user-attachments/files/17870732/stacktrace.txt)

**Comment by RaphaelAmbrosiusC0st3au** [comment]
Same happens for the "large panel" as well. After placing any control it CTDs the server.

**Comment by Panakotta00** [comment]
The issue actually probably is more related to placing a module onto a panel, than the panel. At least thats what the crash report tells me, and which makes sense and should be fixed with the next update. (v0.3.30)

If that is not the case, feel free to reopen the issue.
