### ISSUE TITLE
computer.reset() doesn't

### ISSUE THREAD

**Issue by kfpopeye** [Panakotta00/FicsIt-Networks#364]
computer.reset() doesn't seem to restart the computer. The following code will print the computer.log to the console but then the computer just shuts down.

`
function getContainerByHash(hash)
 local containers = getContainers()
 if not containers then perror("Containers was nil") end
 for _, cntr in pairs(containers) do
  if (cntr.hash == hash) then return cntr end
 end
 computer.log(3, "getContainerByHash(): Hash: " .. hash .. " not found.")
 computer.reset()
end
`

**Comment by Panakotta00** [comment]
should be fixed with latest
