### ISSUE TITLE
The area of getLastVehicle() from the vehicle scanner does not match the location of the signal

### ISSUE THREAD

**Issue by Bommik** [Panakotta00/FicsIt-Networks#82]
The position in which the vehicle scanner returns the vehicle with `getLastVehicle()` does not match with the position where the signal is triggered. When a vehicle drives through the vehicle scanner, the `OnVehicleEnter` signal is triggered, but the vehicle scanner only returns the vehicle in an area round about 2 m after this point with `getLastVehicle()`.
If you drive a factory cart slowly through the vehicle scanner, these two points match. unfortunately not with the other vehicles.

#### To reproduce you need: ####
- 1x Computer
   - 1x EEPROM
   - 1x CPU
   - 1x RAM
- 1x Vehicle Scanner
- 1x Vehicle

#### How to reproduce: ####
1. run the code
2. Drive the vehicle through the vehicle scanner
3. as long as you are in the dead zone the computer beeps.
4. if `getLastVehicle()` returns the vehicle, the computer prints the time you were in the dead zone as well as the approximate distance

#### I used this code for testing: ####
```LUA
vhScanner = component.proxy("...")
event.ignoreAll()
event.listen(vhScanner)
event.clear()

function round(num, numDecimalPlaces)
  local mult = 10^(numDecimalPlaces or 0)
  return math.floor(num * mult + 0.5) / mult
end

x=0

while true do
 e,_,vehicle = event.pull()
 if tostring(e) == "OnVehicleEnter" then
  start = computer.millis()
  speedStart = vehicle.speed 
  while not vhScanner:getLastVehicle() do
   computer.beep()
  end
  stop = computer.millis()
  speedStop = vehicle.speed
  time = (stop-start)/1000
  speedAvg = (speedStart+speedStop)/200
  x=x+1
  print("--------- "..x.." ---------")
  print("t="..time,"(Seconds)")
  print("v="..round(speedAvg,2),"(Meter/Seconds)")
  print("s="..round(speedAvg*time,2),"(Meter)")
 end
end
```

**Comment by Panakotta00** [comment]
I still dont really understand...
